
// TODO: add targets from params
const TARGETS = [
  'configurationformat',
  'windowmode',
  'profile',
  'llcsocketdata',
  'languageselect',
  'textsizeselect',
  'measurementsystem',
  'machineparameters',
  'llcparameters',
  'llc',
  'labelprinter',
  'emaillist',
  'emailconnection',
  'toolpositionlimits',
  'tooldef',
  'tooldef_1',
  'tooldef_2',
  'tooldef_3',
  'tooldef_4',
  'tooldef_5',
  'tooldef_6',
  'tooldef_7',
  'tooldef_8',
  'tooldef_9',
  'tooldef_10',
  'tooldef_11',
  'tooldef_12',
  'tooldef_13',
  'tooldef_14',
  'tooldef_15',
  'tooldef_16',
  'tooldef_17',
  'tooldef_18',
  'tooldef_19',
  'tooldef_20',
  'analoguedisplay',
  'analoguedisplay_0',
  'analoguedisplay_1',
  'analoguedisplay_2',
  'analoguedisplay_3',
  'analoguedisplay_4',
  'analoguedisplay_5',
  'switch',
  'settings'
]

module.exports = TARGETS
